### ISSUE TITLE
Dodati aktuare

### ISSUE THREAD

**Issue by lmiladinovic99** [RAF-SI-2021/Banka-Back#187]
Treba uraditi sledeće:
* Izmeniti korisnički servis dodavanjem novih atributa (limit, limit iskorišćen, zahtevati odobravanje svake porudžbine) u model tako da postoje supervizori i agenti
* Agenta može nadgledati bilo koji supervizor, ne postoji veza supervizor-agent

**Comment by xmudrii** [comment]
Vezano za #115.

**Comment by xmudrii** [comment]
Fixed by #217
